In [2]:
#### Homework 1 ####
### import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
###Question 1
#pandas version
pd.__version__

'1.5.3'

In [6]:
###Question 1
#read data
data = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"
!wget $data 

--2023-09-15 10:13:19--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: 'housing.csv'

housing.csv         100%[===================>]   1.36M  --.-KB/s    in 0.1s    

2023-09-15 10:13:19 (10.5 MB/s) - 'housing.csv' saved [1423529/1423529]



In [61]:
###Question 1
#read data with pandas and store in df
df = pd.read_csv(data)
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [13]:
###Question 2
#How many columns are in the dataset?
len(df.columns)

10

In [18]:
##Question 3
#Which columns in the dataset have missing values?
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [31]:
###Question 4
#How many unique values does the ocean_proximity column have?
df.ocean_proximity.nunique()

5

In [32]:
###Question 5
#What's the average value of the median_house_value for the houses located near the bay?
df[df["ocean_proximity"]=="NEAR BAY"].median_house_value.mean()

259212.31179039303

In [56]:
###Question 6
#Calculate the average of total_bedrooms column in the dataset.
print("average total bedrooms with nan", df.total_bedrooms.mean())
mean_total_bedrooms = df.total_bedrooms.mean()
print("total bedrooms nan values", df["total_bedrooms"].isnull().sum())

average total bedrooms with nan 537.8705525375618
total bedrooms nan values 207


In [58]:
#Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
df.total_bedrooms = df.total_bedrooms.fillna(mean_total_bedrooms)
print("total bedrooms nan values", df["total_bedrooms"].isnull().sum())

total bedrooms nan values 0


In [59]:
#Now, calculate the average of total_bedrooms again.
print("average total bedrooms with nan replaced with mean", df.total_bedrooms.mean())
#Has it changed?
#Not in the first 3 decimal digits

average total bedrooms with nan replaced with mean 537.8705525375617


In [77]:
###Question 7
df.head()
df.ocean_proximity.unique()
#Select all the options located on islands.
df_islands = df[df.ocean_proximity=="ISLAND"]
#Select only columns housing_median_age, total_rooms, total_bedrooms.
df_islands = df_islands[["housing_median_age", "total_rooms", "total_bedrooms"]]
display(df_islands)
#Get the underlying NumPy array. Let's call it X.
X = df_islands.values
print("X",X)
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T.dot(X)
print("XTX",XTX)
#Compute the inverse of XTX.
XTX_inv = np.linalg.inv(XTX)
print("XTX_inv",XTX_inv)
#Create an array y with values [950, 1300, 800, 1000, 1300].
y=[950, 1300, 800, 1000, 1300]
print("y",y)
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv.dot(X.T).dot(y)
print("w",w)
#What's the value of the last element of w?
print("w2", w[-1])

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

X [[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]
XTX [[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]
XTX_inv [[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]
y [950, 1300, 800, 1000, 1300]
w [23.12330961 -1.48124183  5.69922946]
w2 5.699229455065594
